# Generated by Django 4.0.1 on 2022-01-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_no',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
